import marketSnapshot from '../../data/markets/2026-08-23T184126-0400-paired-win-totals.json';
import kalshiSnapshot from '../../data/markets/20260823T232141.768Z-kalshi-nfl-win-ladders.json';
import teamRegistry from '../../data/nfl/teams.json';

export type CategoryId = 'qb' | 'coaching' | 'ol' | 'skill';

export type Team = {
  id: string;
  name: string;
  abbr: string;
  conference: 'AFC' | 'NFC';
  division: 'East' | 'North' | 'South' | 'West';
};

export type Evidence = {
  team: string;
  rank: number;
  tier: string;
  tierLabel: string;
  subject: string;
  people: string[];
  positives: string[];
  concerns: string[];
  context: string[];
  lines: [number, number];
};

export type Market = {
  line: number;
  over: string;
  under: string;
  book: string;
  hold: number;
  noVigOver: number;
  medianBracket: string;
  expectedWins: number | null;
  coverageLabel: string;
  confidence: string;
  thresholdCount: number;
  pairedQuoteCount: number;
  marketRank: number;
  marketIndex: number;
  sportsbookMarketRank: number;
  expectedWinsBid: number;
  expectedWinsAsk: number;
  kalshiAverageSpread: number;
};

const E = (team: string, rank: number, tier: string, tierLabel: string, subject: string, people: string[], positives: string[], concerns: string[], context: string[], lines: [number, number]): Evidence => ({ team, rank, tier, tierLabel, subject, people, positives, concerns, context, lines });

export const teams: Team[] = teamRegistry.map(team => ({
  id: team.abbr.toLowerCase(),
  name: team.name,
  abbr: team.abbr,
  conference: team.conference as Team['conference'],
  division: team.division as Team['division'],
}));

export const sourceMeta = {
  qb: { label: 'Quarterbacks', source: 'https://pocketcasts.com/podcasts/6bd8a7b0-f1fd-0132-1157-059c869cc4eb/4e657898-f2f9-4a05-9cb6-e5a27f8c3cf2/transcript', words: 11774 },
  coaching: { label: 'Coaching staffs', source: 'https://pocketcasts.com/podcasts/6bd8a7b0-f1fd-0132-1157-059c869cc4eb/536e0274-0383-4b97-904b-986237b1b6d8/transcript', words: 12185 },
  ol: { label: 'Offensive lines', source: 'https://pocketcasts.com/podcasts/6bd8a7b0-f1fd-0132-1157-059c869cc4eb/736ccaf1-f5e8-4b45-813f-cc8e25075f74/transcript', words: 12196 },
  skill: { label: 'Skill positions', source: 'https://pocketcasts.com/podcasts/6bd8a7b0-f1fd-0132-1157-059c869cc4eb/98f3433e-7487-4c23-87ee-9bef34eaa4dc/transcript', words: 12504 },
} as const;

export const marketSource = {
  label: marketSnapshot.source.label,
  url: marketSnapshot.source.url,
  updated: 'Per-quote update time unavailable',
  retrieved: 'Aug. 23, 2026, 6:41 PM ET',
  note: marketSnapshot.source.update_note,
};

export const kalshiMarketSource = {
  label: kalshiSnapshot.source.label,
  url: kalshiSnapshot.source.api_url,
  documentation: kalshiSnapshot.source.api_documentation,
  retrieved: 'Aug. 23, 2026, 7:21 PM ET',
  authenticated: kalshiSnapshot.source.authentication.verified,
};

type SnapshotTeam = {
  primary: { line:number; reference_book:string; over_odds:number; under_odds:number; reference_hold:number; consensus_no_vig_over_probability:number };
  fair_median_bracket: { display:string };
  expected_wins: { value:number|null };
  coverage: { label:string; confidence:string; threshold_count:number; paired_quote_count:number };
  price_adjusted_market_rank:number;
  price_adjusted_order_index:number;
};

type KalshiSnapshotTeam = {
  coverage: { threshold_count:number; all_17_tails:boolean };
  expected_wins: { midpoint_estimate:number; bid_bound:number; ask_bound:number };
  average_spread:number;
  expected_win_rank:number;
};

const snapshotTeams = marketSnapshot.teams as Record<string,SnapshotTeam>;
const kalshiTeams = kalshiSnapshot.teams as Record<string,KalshiSnapshotTeam>;
const american = (odds:number) => odds > 0 ? `+${odds}` : String(odds);

export const markets: Record<string, Market> = Object.fromEntries(Object.entries(snapshotTeams).map(([abbr,market]) => [abbr,{
  line: market.primary.line,
  over: american(market.primary.over_odds),
  under: american(market.primary.under_odds),
  book: market.primary.reference_book,
  hold: market.primary.reference_hold,
  noVigOver: market.primary.consensus_no_vig_over_probability,
  medianBracket: market.fair_median_bracket.display,
  expectedWins: kalshiTeams[abbr].expected_wins.midpoint_estimate,
  expectedWinsBid: kalshiTeams[abbr].expected_wins.bid_bound,
  expectedWinsAsk: kalshiTeams[abbr].expected_wins.ask_bound,
  coverageLabel: 'Kalshi full ladder',
  confidence: kalshiTeams[abbr].average_spread <= 0.05 ? 'high' : kalshiTeams[abbr].average_spread <= 0.10 ? 'medium' : 'low',
  thresholdCount: kalshiTeams[abbr].coverage.threshold_count,
  pairedQuoteCount: market.coverage.paired_quote_count,
  marketRank: kalshiTeams[abbr].expected_win_rank,
  marketIndex: kalshiTeams[abbr].expected_wins.midpoint_estimate,
  sportsbookMarketRank: market.price_adjusted_market_rank,
  kalshiAverageSpread: kalshiTeams[abbr].average_spread,
}])) as Record<string,Market>;

export const sportsbookMarketAudit = marketSnapshot.audit;
export const marketAudit = kalshiSnapshot.audit;
export const winAggregates = kalshiSnapshot.aggregates;
export const betCandidates = kalshiSnapshot.candidates;

export const qbEvidence: Evidence[] = [
  E('BUF',1,'1','Best of the best','Josh Allen',['Josh Allen'],['All the physical tools; Anderson says he has sharply reduced the mistakes.','His individual playoff performance has generally been excellent despite the no-Super-Bowl criticism.'],['No championship yet remains the public counterargument.'],['Allen takes the No. 1 spot after Patrick Mahomes held it for seven straight editions.'],[188,278]),
  E('KC',2,'1','Best of the best','Patrick Mahomes',['Patrick Mahomes','Travis Kelce'],['Still receives the playoff and championship benefit of the doubt; Anderson cites a 10.3-win pace and a 6–1 playoff mark with a ring during the recent statistical downswing.'],['First major injury: torn ACL.','EPA, success rate and completion-over-expected measures had already slipped to roughly 10th over the prior two years.','The aging and weakened skill group is part of the statistical context.'],['First time outside No. 1 in Anderson’s seven Mahomes-era rankings.'],[191,293]),
  E('CIN',3,'2','The AFC North bites back','Joe Burrow',['Joe Burrow'],['Anderson is least worried about Burrow’s injuries, viewing them as mostly fluky and non-repeatable.','Pocket-based passing should age more safely than a game built heavily on legs.'],['Missed roughly half of the prior season and has accumulated several injuries.'],['Same top-four group as the prior edition.'],[287,365]),
  E('BAL',4,'2','The AFC North bites back','Lamar Jackson',['Lamar Jackson'],['A large bank of elite prior seasons supports throwing out one bad year.','A new coaching system offers a reset.'],['Hamstring and knee issues removed much of his mobility and the numbers cratered.','Aging and leg dependence create a sharper potential decline curve; playoff concerns remain.'],['Anderson thinks the market may be overreacting to an injury-compromised season, but Lamar is the most concerning injury case among Mahomes, Burrow and Jackson.'],[287,365]),
  E('GB',5,'3','Great regardless of surroundings','Jordan Love',['Jordan Love','Matt LaFleur'],['No. 2 in EPA/play, No. 3 in completion over expected and No. 4 in PFF grade in the prior season.','At least nine wins in every season; fourth in playoff EPA/play over the cited stretch.','Hunts explosive plays and has carried weak blocking, inconsistent weapons, defense and special teams.'],['Mistakes are loud and ugly; the surrounding Green Bay setup is not strong.'],['The transcript contains one garbled “all-time leader” rate claim, retained as an audit exception rather than guessed. Anderson says Green Bay struggles would likely come in spite of Love.'],[374,443]),
  E('NE',6,'3','Great regardless of surroundings','Drake Maye',['Drake Maye','A.J. Brown','Romeo Doubs'],['Top two in essentially every key metric and led the league in scramble yards; nearly won MVP.','Produced without strong blocking or weapons, which are now improved by Brown and Doubs.','Anderson sees a path into the very top tier with another full regular season plus better playoffs.'],['Was poor in the playoffs despite the Super Bowl run; needs to prove the elite level for a second year.'],['Anderson would have voted Maye MVP.'],[446,500]),
  E('DAL',7,'3','Great regardless of surroundings','Dak Prescott',['Dak Prescott','CeeDee Lamb','George Pickens','Tony Romo'],['Faced the third-most pressure but ranked No. 1 by PFF under pressure.','Top-five overall PFF grade in two of three years and No. 1 clutch grade in the prior year.','Anderson credits him with a 10.2-win regular-season pace and the ability to raise an offense’s floor.'],['Two-and-five playoff record; high-profile turnovers and Dallas scrutiny stay loud.'],['Compared with Tony Romo as a consistently top-quarter quarterback who receives extra criticism because of the star on the helmet.'],[506,608]),
  E('LAR',8,'4','The litmus tests','Matthew Stafford',['Matthew Stafford','Sean McVay','Puka Nacua','Davante Adams'],['Reigning MVP; 47 big-time throws led the league by 16, and he led in first downs, passing yards and passing TDs.','Still gets full credit for executing an elite offense and rises from 14th to eighth.'],['Had an almost ideal ecosystem: five highly graded linemen, elite rushing/play calling, two star receivers and a good defense.','At 38 with injury history, pressure and injuries around him can expose limited creation.'],['Gallant argued for a top-five “reigning MVP” rule; Anderson’s swap test says the seven above him would equal him in Los Angeles and improve their own teams.'],[614,845]),
  E('LAC',9,'4','The litmus tests','Justin Herbert',['Justin Herbert','Mike McDaniel','Joe Alt','Rashawn Slater'],['Undeniable tools; the best ecosystem of his career may arrive with McDaniel and a healthier line.'],['Metrics have generally been fringe top ten rather than elite.','0–3 and personally poor in the playoffs; both tackles missing most of last year is mitigating context.'],['A one-year “prove it” drop from the top tier; Anderson expects a plausible rebound.'],[851,926]),
  E('SF',10,'4','The litmus tests','Brock Purdy',['Brock Purdy','Kyle Shanahan','Jimmy Garoppolo','Mac Jones'],['Jumps from 18th after showing pocket navigation and off-script creation beyond the system.','The Mac Jones comparison convinced Anderson this is not merely Shanahan production.'],['The system remains a major contributor; extra creation brings mistakes and downside.'],['Anderson says Purdy has won him over and now belongs in the top ten.'],[926,1028]),
  E('JAX',11,'4','The litmus tests','Trevor Lawrence',['Trevor Lawrence','Liam Coen'],['Final seven-game pace: roughly 4,500 passing yards and 54 TDs.','Year two with Coen and a talented receiving group leave room to climb a tier.','A 10% receiver drop rate provided meaningful drag.'],['Breakout came against a soft schedule and must be sustained.'],['The AFC South order is unusually volatile; Anderson still likes Lawrence best.'],[1028,1082]),
  E('TB',12,'4','The litmus tests','Baker Mayfield',['Baker Mayfield','Mike Evans','Chris Godwin'],['Started 5–1 with wins over Houston, Seattle and San Francisco and briefly entered the MVP conversation despite missing Evans and Godwin.','Scrambling and creation raise the ceiling; a much better line should stabilize the setup.'],['After a shoulder injury, fell to 27th in EPA/play; sacks, turnovers and big mistakes remain part of the Baker package.'],['Anderson calls this ranking partly a projection of the improved environment.'],[926,1023]),
  E('CHI',13,'5','Upside swings','Caleb Williams',['Caleb Williams','Ben Johnson'],['In one Johnson season, deep-ball PFF grade rose from 36 to top five; sack rate fell from 11% to 4%.','Time to throw fell by a full second and pressure-to-sack rate improved from 28% to 11%.','One-of-one home-run ability supports a future top-ten case.'],['Still needs more routine completions and chain-moving “vegetables” between spectacular plays.'],['Anderson repeatedly nudged Williams upward because the trajectory is so positive.'],[1277,1418]),
  E('WAS',14,'5','Upside swings','Jayden Daniels',['Jayden Daniels'],['His rookie year remains the best single season between him and Caleb Williams; rushing gives elite upside.'],['Injuries and a leg-dependent game create durability risk.','A weak line and coaching setup leave him carrying too much; the transcript invokes an RGIII-style caution.'],['Anderson puts Caleb ahead on trajectory, not because Daniels has shown less peak production.'],[1421,1469]),
  E('PHI',15,'5','Upside swings','Jalen Hurts',['Jalen Hurts','Sean Mannion','Nick Sirianni','A.J. Brown'],['Resume is elite: 14, 11, 12 and 13 wins across four years, two Super Bowl trips and a Super Bowl MVP.','Goal-line value remains exceptional.'],['Fewer designed runs and visibly reduced speed may be eroding a key advantage.','Career-long pressure and middle-of-field passing problems meet a new offense built to attack the middle; Brown is gone.'],['Hardest player to rank: Anderson says No. 15 could be five spots high or low and frames 2026 as a possible Hurts/Sirianni breaking point.'],[1106,1274]),
  E('HOU',16,'5','Upside swings','C.J. Stroud',['C.J. Stroud'],['Poor blocking and no run game materially worsened the environment.'],['31st in PFF grade; Anderson doubts a top-five-to-seven ceiling and says Stroud actively dragged down a strong playoff roster.'],['May belong more naturally in the environment-dependent tier; the upside label is increasingly strained.'],[1283,1340]),
  E('MIN',17,'5','Upside swings','Kyler Murray',['Kyler Murray','Kevin O’Connell','J.J. McCarthy'],['Best ecosystem of his career: strong weapons, potentially better line and O’Connell.','Former No. 1 pick and former in-season MVP favorite; about a .500 QB when healthy in a workable setting.','Acquisition cost was effectively zero.'],['Only about 10 games per year over the last four; fit and health are major unknowns.'],['Last quarterback Anderson can imagine driving a meaningful playoff run; McCarthy would have made the room bottom five.'],[1469,1568]),
  E('DET',18,'6','Win with them, not because of them','Jared Goff',['Jared Goff'],['A team can win deep into January with this style of quarterback.'],['Big-game situations leave Anderson and, he argues, coaches hesitant; the offense keeps “training wheels” on.'],['Grouped with Darnold, Nix and Smith as quarterbacks who can win with a team but also lose games for it.'],[1571,1679]),
  E('SEA',19,'6','Win with them, not because of them','Sam Darnold',['Sam Darnold'],['Reigning Super Bowl champion proves this tier can win it all in the right structure.'],['Anderson still sees limited trait-driven upside and big-game doubt.'],['The distinction is “with him,” not “because of him.”'],[1571,1676]),
  E('DEN',20,'6','Win with them, not because of them','Bo Nix',['Bo Nix','Jaylen Waddle'],['Second in big-time throws and top three in PFF grade on deep passes; adds scrambling upside.','Waddle supplies the vertical weapon Denver lacked.'],['Still grouped with quarterbacks coaches may protect in the biggest moments.'],['Anderson’s clear choice to jump out of this tier.'],[1571,1712]),
  E('NYJ',21,'6','Win with them, not because of them','Geno Smith',['Geno Smith'],['A .500 starter in four of six seasons; Anderson believes a strong roster could still salvage a season with him.','Last year’s line and coaching were serious mitigating factors.'],['Prior season was awful; at 35 he may simply be washed. Gallant predicts another interception-heavy year.'],['Anderson considered rank 26, then kept him in the tier on conviction.'],[1715,1778]),
  E('LV',22,'7','No. 1-pick wild cards','Fernando Mendoza / Kirk Cousins',['Fernando Mendoza','Kirk Cousins','Clint Kubiak'],['Kubiak’s system looks like a strong early fit for Cousins and an eventual runway for Mendoza.','Historical claim in the episode: No. 1 picks since Jameis Winston averaged 3.3 rookie wins and 8.6 sophomore wins.'],['Ranking is projection; Cousins is expected to begin the season and Mendoza may not take over immediately.'],['Anderson is already interested in the 2027 Raiders.'],[1781,1883]),
  E('TEN',23,'7','No. 1-pick wild cards','Cam Ward',['Cam Ward'],['Treat the coming year as the development season lost to a dysfunctional rookie setup; history says No. 1 picks often improve sharply in year two.'],['Dead last in EPA and success rate, league-high 55 sacks, third-last PFF grade.'],['No blocking, run game or receivers and a midseason coaching firing made year one resemble Trevor Lawrence under Urban Meyer.'],[1781,1877]),
  E('NO',24,'8','We just do not know yet','Tyler Shough',['Tyler Shough','Taysom Hill'],['Went 5–4 with fringe top-20 metrics as a second-round rookie; adds useful goal-line rushing.'],['Wins came against a weak slate; 25% pressure-to-sack rate, long injury history and advanced rookie age cap the development case.'],['Could reasonably rise toward No. 20, but Anderson needs more than nine games.'],[1886,2018]),
  E('NYG',25,'8','We just do not know yet','Jaxson Dart',['Jaxson Dart','Jameis Winston'],['Deep ball, rushing and home-run creation supply meaningful upside; Winston is a credible high-variance backup.'],['Invites pressure and major hits; roughly four concussion checks in the prior year demand self-preservation.'],['Anderson prefers Dart’s upside to Shough’s steadier profile even though the ordinal order has Shough first.'],[1886,2021]),
  E('MIA',26,'8','We just do not know yet','Malik Willis',['Malik Willis'],['Only the uncertainty and rushing/creation case keep a sliver of upside.'],['Gallant calls the Miami assignment a raw deal and expects a horrible season; the episode largely declines to make a positive case.'],['Thin transcript treatment is itself part of the source record.'],[1886,1898]),
  E('CAR',27,'9','Unfortunately, we probably do know','Bryce Young',['Bryce Young'],['Clearly improved year over year and played well in a playoff game.'],['“Improved” is not “good”; Anderson views him as one of the league’s weakest starters and a path to middling draft position rather than a franchise answer.'],['Rank 27 is offered as both recognition of improvement and a damning ceiling statement.'],[2033,2120]),
  E('IND',28,'9','Unfortunately, we probably do know','Daniel Jones',['Daniel Jones'],['Best rebound candidate in the tier; opened 7–1 and a healthy version could fit near the Goff/Nix group.'],['Finished 1–4, outside top 20 in PFF grade and second in turnover-worthy-play rate; now returning from a torn Achilles.'],['Anderson distrusts glowing camp reports without preseason evidence and notes recent older-QB Achilles precedents.'],[2150,2228]),
  E('ATL',29,'9','Unfortunately, we probably do know','Tua Tagovailoa / Michael Penix Jr.',['Tua Tagovailoa','Michael Penix Jr.'],['Two plausible options create two chances for one quarterback to get hot; Tua once piloted an elite offense.'],['Anderson bluntly says both may be around the 40th-best-QB level and does not like either option.'],['The rank represents Atlanta’s tandem rather than confidence in one starter.'],[2123,2189]),
  E('PIT',30,'9','Unfortunately, we probably do know','Aaron Rodgers',['Aaron Rodgers'],[],['No longer even a game manager: pressure aversion, more mistakes and no remaining upside.'],['Anderson dislikes replacing the Tomlin-era Steelers with a Rodgers-led version.'],[2033,2081]),
  E('ARI',31,'9','Unfortunately, we probably do know','Jacoby Brissett',['Jacoby Brissett'],['Veteran baseline and prior chemistry with Arizona’s pass catchers offer stability.'],['Placed near the bottom with no meaningful ceiling case discussed.'],['The transcript spends little individual time on Brissett; no extra certainty is invented.'],[2033,2189]),
  E('CLE',32,'10','The room, not one answer','Deshaun Watson / Browns room',['Deshaun Watson','Dillon Gabriel','Shedeur Sanders'],[],['Watson was last good in 2020 and still appears likely to beat out the other options.'],['The speakers consider the entire room so poor it is barely worth extended discussion.'],[2231,2264]),
];

export const coachingEvidence: Evidence[] = [
  E('SF',1,'1','The two standards','Kyle Shanahan staff',['Kyle Shanahan','Raheem Morris'],['Shanahan is Anderson’s preferred offensive play caller and repeatedly keeps the offense productive through injuries.','Raheem Morris is a trusted, proven defensive coordinator and the tiebreaker over Los Angeles.'],['Shanahan can be conservative in-game and the special-teams operation has lagged.'],['The staff produced a top-ten offense even without a strong line or healthy receiver group.'],[221,316]),
  E('LAR',2,'1','The two standards','Sean McVay staff',['Sean McVay','Chris Shula'],['McVay gets the edge as a head coach, in-game manager and staff builder; his organization keeps retaining and replacing good coaches.','Shula is a rising defensive coordinator and possible future head coach.'],['The offense has occasionally fallen apart when injuries remove its ideal pieces.','Shula has less proven coordinator history than Morris.'],['Essentially tied with San Francisco; coordinator confidence decides the order.'],[221,316]),
  E('CHI',3,'2','Something old, something new','Ben Johnson staff',['Ben Johnson','Dennis Allen'],['Johnson delivered everything hoped for as an offensive designer and developer.','Allen supplies an experienced defensive counterweight and has a history of creating turnovers.'],['Turnover production can regress even if it has been relatively sticky for Allen.'],['Better health and personnel should reinforce a staff already validated in year one.'],[323,423]),
  E('LAC',4,'2','Something old, something new','Jim Harbaugh staff',['Jim Harbaugh','Mike McDaniel','Chris O’Leary','Jesse Minter'],['Harbaugh has won at least 11 games in five of six NFL seasons and establishes a high organizational floor.','McDaniel is described as an S-tier offensive play caller and a massive upgrade from Greg Roman.','O’Leary brings the aggressive Minter/Macdonald tree and turned Western Michigan around in one year.'],['Losing Jesse Minter leaves an unproven defensive transition.'],['Anderson credits Harbaugh for changing staff instead of preserving a weak offense.'],[423,500]),
  E('KC',5,'2','Something old, something new','Andy Reid staff',['Andy Reid','Eric Bieniemy','Steve Spagnuolo','Andy Heck','Dave Toub'],['Reid remains an elite offensive mind; Spagnuolo is a top-ten defensive caller.','Heck and Toub are described as legendary line and special-teams coaches.'],['Reid is in the twilight of his career; Bieniemy’s return is familiar rather than fresh and may not solve recent offensive stagnation.'],['First edition in which Anderson did not place Kansas City in the top tier.'],[335,405]),
  E('SEA',6,'2','Something old, something new','Mike Macdonald staff',['Mike Macdonald','Jay Harbaugh','Brian Fleury','Clint Kubiak'],['Macdonald is Anderson’s clear No. 1 defensive play caller, mixing organized chaos with a strong culture.','Jay Harbaugh may be the league’s best special-teams coach and mastered the new kickoff environment.'],['Fleury is a new and unproven offensive play caller; losing Kubiak creates real regression risk.'],['The staff ranks far above Seattle’s individual offensive units.'],[500,604]),
  E('JAX',7,'2','Something old, something new','Liam Coen staff',['Liam Coen','Anthony Campanile','Heath Farwell','Baker Mayfield','Trevor Lawrence'],['Coen won 13 games, set a strong culture and reinforced his elite play-calling reputation after helping both Mayfield and Lawrence.','Campanile brings linebacker/run-defense and Green Bay credentials; Farwell is a top-ten special-teams coach.'],['Some coordinator confidence is still projection rather than a long track record.'],['Anderson found no clear staff weakness and did not initially expect Jacksonville this high.'],[595,670]),
  E('MIN',8,'3','Two strengths, one weakness','Kevin O’Connell staff',['Kevin O’Connell','Brian Flores','Kyler Murray'],['O’Connell and Flores give Minnesota strong leadership and defensive play calling; O’Connell is 43–25 over four years and managed 9–8 with bad quarterback play.'],['The offense ranked 29th in DVOA last year and had prior finishes of roughly 20th, 23rd and 15th—never top 14.','A bank of close wins is unlikely to repeat indefinitely.'],['Murray is the test of whether O’Connell can create a truly top offense rather than merely a winning floor.'],[677,794]),
  E('DEN',9,'3','Two strengths, one weakness','Sean Payton staff',['Sean Payton','Davis Webb','Vance Joseph'],['Payton has produced at least seven wins in all 18 head-coaching seasons.','Joseph runs an elite, aggressive defense.','Turning the offense over to 31-year-old Webb introduces fresh upside.'],['Payton reached 12 wins only six times in 18 seasons and benefited from close-game results; Webb has never called NFL plays.'],['The handoff can break a perceived Payton ceiling or expose the risk of an untested caller.'],[794,860]),
  E('HOU',10,'3','Two strengths, one weakness','DeMeco Ryans staff',['DeMeco Ryans','Nick Caley'],['Ryans has 10, 10 and 12 wins plus a playoff victory in each season and fields an elite defense.','Caley comes from McVay, Shanahan and Josh McDaniels branches.'],['Caley’s first year calling the offense was poor and must show a year-two leap.'],['Strong defense and organizational results keep Houston top ten despite offensive uncertainty.'],[860,908]),
  E('GB',11,'3','Two strengths, one weakness','Matt LaFleur staff',['Matt LaFleur','Jonathan Gannon','Malik Willis'],['LaFleur is an elite game-plan and scheme designer and has even won with Willis.'],['His sequencing can frustrate; Gannon’s passive, vanilla defense is viewed as a floor without much ceiling.'],['Offensive strength outweighs the defensive weakness.'],[908,950]),
  E('IND',12,'3','Two strengths, one weakness','Shane Steichen staff',['Shane Steichen','Lou Anarumo'],['Steichen is aggressive and excels at the run, play action and deep passing; Indianapolis briefly produced a historic No. 1 offense.','He has won nine, eight and eight games with unstable quarterback play.'],['Anderson considers Anarumo overrated and cites weak underlying defensive results.'],['The staff closes the group that has two clear strengths and one weakness.'],[950,986]),
  E('NYG',13,'4','Rage-bait central','John Harbaugh staff',['John Harbaugh','Chris Horton','Matt Nagy','Greg Roman','Brian Callahan','Dennard Wilson'],['Harbaugh was Anderson’s No. 1 head coach a year earlier and gives culture, organization and floor.','Horton is an elite special-teams coach; Wilson has had some defensive success.'],['Nagy, Roman and Callahan form an offensive trio Anderson ranks 32nd for play calling.'],['Harbaugh’s floor raises the Giants from 31st to 13th despite a major offensive-coordinator penalty.'],[998,1081]),
  E('PHI',14,'4','Rage-bait central','Nick Sirianni staff',['Nick Sirianni','Vic Fangio','Sean Mannion','Jeff Stoutland','Jalen Hurts'],['Fangio remains an outstanding defensive coordinator; Sirianni’s résumé includes elite team results.'],['Mannion is the fourth offensive coordinator in four years and emphasizes the middle of the field, a poor match for Hurts.','Stoutland is gone after a contentious finish.'],['Anderson calls Sirianni the “Russell Westbrook” of coaches: the good and bad are inseparable, and 2026 may be an endpoint.'],[1081,1160]),
  E('DET',15,'4','Rage-bait central','Dan Campbell staff',['Dan Campbell','John Morton','Drew Petzing','Kelvin Sheppard','Ben Johnson'],['Campbell remains a strong culture setter.'],['Life after Johnson has been difficult: Morton was fired midyear, Petzing’s Arizona work was not persuasive and Sheppard’s defensive results were weak.'],['Detroit needs to prove it has found the next staff iteration rather than simply extending the old one.'],[1160,1217]),
  E('NE',16,'4','Rage-bait central','Mike Vrabel staff',['Mike Vrabel','Josh McDaniels'],['Vrabel raised the floor from four wins to 14 and clearly installed the right structure for the turnaround.'],['The operation is conservative; McDaniels is considered an average caller with a limited ceiling.'],['The question changes from “can this work?” to whether the same staff can win at a Super Bowl ceiling.'],[1148,1251]),
  E('BAL',17,'5','We got next','Jesse Minter staff',['Jesse Minter','Declan Doyle','Dwayne Ledford','Mike Macdonald','Sean Payton','Ben Johnson'],['Minter is Anderson’s favorite new head coach and likely a top-five defensive caller/culture setter.','Doyle carries Johnson and Payton influences; Ledford is a strong line coach.'],['All three central roles are new, so the ranking stays conservative.'],['Drops from its perennial top-three Harbaugh perch, but could crack the top ten by year-end.'],[1253,1333]),
  E('DAL',18,'5','We got next','Brian Schottenheimer staff',['Brian Schottenheimer','Clayton Adams','Christian Parker','CeeDee Lamb','George Pickens','Vic Fangio'],['Schottenheimer’s design and YAC concepts unlocked Lamb and Pickens.','Adams creates a premier gap/downhill run game.','Parker is a highly regarded Fangio-tree defensive-backs coach.'],['Parker is a first-time caller and Fangio disciples have not universally succeeded.'],['Anderson admits last year’s No. 32 ranking was wrong; Dallas may finish top ten.'],[1334,1436]),
  E('NO',19,'5','We got next','Kellen Moore staff',['Kellen Moore','Brandon Staley'],['Moore uses motion and tempo creatively; Staley is again succeeding as a coordinator.','New Orleans is one of only five teams with both offensive and defensive callers in Anderson’s top 12.'],['Staley’s radical system invites the run and can fail badly when opponents exploit it.'],['Coaching is a central reason for the Saints sleeper case.'],[1436,1520]),
  E('CAR',20,'6','They’re fine','Dave Canales staff',['Dave Canales'],['No staff turnover and steady, average competency are meaningful improvements over prior Carolina regimes.'],['No individual component projects as a major advantage: head coach 17th, offense 14th, defense 17th.'],['Anderson calls this the league’s most average staff—and means that as acceptable progress.'],[1520,1585]),
  E('WAS',21,'6','They’re fine','Dan Quinn staff',['Dan Quinn','David Blough','Daronte Jones','Larry Izzo','Kliff Kingsbury','Ben Johnson','Vance Joseph'],['Blough is a 31-year-old offensive caller with Lions/Johnson influence; Jones brings aggressive Vikings/DB concepts.','Izzo is among the league’s best special-teams coaches.'],['Anderson sees smoke and mirrors in Quinn’s head-coaching success; aggressive defense can collapse without enough talent.'],['The optimism comes from the new coordinators, not Quinn; moving on from Kingsbury is viewed as addition by subtraction.'],[1585,1675]),
  E('TB',22,'6','They’re fine','Todd Bowles staff',['Todd Bowles','Zach Robinson','Liam Coen','Josh Grizzard'],['Bowles has delivered eight to ten wins in four straight years and remains a top-ten defensive caller.','Robinson’s McVay/Mike Gundy background produced a respectable Atlanta offense despite poor quarterback play.'],['Bowles supplies floor rather than ceiling; Tampa has churned offensive coordinators.'],['Anderson thinks Robinson could resemble the successful Coen chapter more than Grizzard’s failed one.'],[1544,1640]),
  E('LV',23,'7A','New-staff floor bets','Clint Kubiak staff',['Clint Kubiak','Rob Leonard','Patrick Graham','Kirk Cousins','Fernando Mendoza'],['Kubiak raises the run-game and line floor and should create easy answers for both quarterbacks.'],['His offenses have faded in the second half; Leonard is an unknown first-time defensive caller and Anderson’s last-ranked DC.'],['If Leonard is merely average, Las Vegas could rise quickly.'],[1727,1845]),
  E('ATL',24,'7A','New-staff floor bets','Kevin Stefanski staff',['Kevin Stefanski','Tommy Rees','Jeff Ulbrich'],['Stefanski is a two-time Coach of the Year and all three principal names carry experience.'],['The group feels like familiar, below-average retreads rather than a new source of advantage.'],['Anderson repeatedly finds these coaches around 18th–23rd and wishes Atlanta had tried something different.'],[1845,1940]),
  E('BUF',25,'7A','New-staff floor bets','Joe Brady staff',['Joe Brady','Jim Leonhard','Josh Allen','Joe Burrow','Sean McDermott'],['Leonhard is an exciting defensive-backs/college-influenced hire.','Continuity should reduce transition cost.'],['Brady is run-heavy and may owe his reputation to Allen and Burrow; keeping an in-house successor blunts the value of firing McDermott.','Leonhard must replace a defense McDermott often maximized.'],['A top-five staff falls to 25th; if the defense misses, Anderson fears a precipitous drop.'],[1940,2035]),
  E('MIA',26,'7A','New-staff floor bets','Jeff Hafley staff',['Jeff Hafley','Bobby Slowik','Kevin Patullo','Chris Tabor','C.J. Stroud','Anthony Campanile'],['Slowik produced Stroud’s best season and can supply efficient, run-heavy floor; Tabor is a top-five special-teams coach.'],['Hafley’s Boston College tenure, departure and turnover-driven Green Bay defense do not inspire confidence; he also benefited from Campanile.','Patullo’s recent work was a disaster.'],['Slowik still lands in Anderson’s top 20 callers, partly because the league has so many new names.'],[1980,2115]),
  E('PIT',27,'7A','New-staff floor bets','Mike McCarthy staff',['Mike McCarthy','Patrick Graham','Aaron Rodgers','Dak Prescott'],['McCarthy has overseen successful offenses; Graham is a rising defensive name.'],['Bad in-game decisions and pass-heavy tendencies persist; much of McCarthy’s success came with Prescott or a younger Rodgers.','Graham is unlikely to extract more than Tomlin’s defensive operation.'],['The new regime feels even less inspiring than the late Tomlin version.'],[1845,1975]),
  E('ARI',28,'7B','Known names, low conviction','Mike LaFleur staff',['Mike LaFleur','Nathaniel Hackett','Nick Rallis','Zach Wilson','Sean McVay'],['Rallis offers unique defensive looks and was sensibly retained; LaFleur carries McVay-tree upside.'],['LaFleur’s only play-calling sample was the Zach Wilson Jets; hiring Hackett is itself treated as a severe negative even though he will not call plays.'],['Anderson’s preferred surprise candidate among the bottom new staffs.'],[2140,2268]),
  E('CLE',29,'7B','Known names, low conviction','Todd Monken staff',['Todd Monken','Mike Rutenberg','Robert Saleh','Gus Bradley'],['Monken is versatile and creative rather than tied to a single style; he built Baltimore’s No. 1 offense.'],['First head-coaching job at age 60 reads as organizational desperation; he lacked counters after Baltimore regressed.','Rutenberg is a first-time caller from defensive trees Anderson distrusts.'],['Play calling earns credit; the head-coach rationale does not.'],[2210,2328]),
  E('TEN',30,'7B','Known names, low conviction','Robert Saleh staff',['Robert Saleh','Brian Daboll','Gus Bradley'],['Saleh has produced solid defensive results; the veteran names may establish a floor.'],['Saleh is vanilla and talent-dependent, Bradley’s low-blitz/high-zone style looks outdated, and Daboll’s long record is mediocre.'],['Anderson calls the trio the “reverse Avengers” and strongly dislikes the fit.'],[2115,2195]),
  E('CIN',31,'8','The holdovers that held on','Zac Taylor staff',['Zac Taylor','Dan Pitcher','Al Golden','Darrin Simmons'],['Under-center offense could finally add answers; Simmons is the special-teams silver lining and Anderson initially liked Golden.'],['The defense was too bad to reward Golden; the staff keeps holding back an elite offense.','Taylor is entering year eight partly because cheap ownership resists change.'],['Could rise into the mid-20s, but every unit must first escape the bottom quartile.'],[2328,2435]),
  E('NYJ',32,'8','The holdovers that held on','Aaron Glenn staff',['Aaron Glenn','Frank Reich'],[],['Glenn cleared out and blamed his staff, now calls plays despite unimpressive Detroit work.','Reich’s Colts and Panthers offenses improved immediately after he left.'],['Anderson sees no defensible way to put another staff last.'],[2328,2406]),
];

export const olEvidence: Evidence[] = [
  E('DEN',1,'1','Consensus No. 1','Five returning starters',['Garrett Bolles','Quinn Meinerz','Sean Payton','Bo Nix'],['Every outside expert Anderson consulted also had Denver first.','All five starters enter a third year together; Bolles allowed no sacks across 802 cited snaps and Meinerz is an anchor.','Quick decisions from Nix plus Payton’s protection design reinforce elite pass blocking.'],['This is a top-five lock more than a historically towering No. 1.'],['Denver ranked second last year and now has the best continuity/weak-link profile.'],[179,296]),
  E('TB',2,'2','Could finish first','Healthy star power',['Tristan Wirfs','Luke Goedeke','Cody Mauch','Zach Robinson'],['Wirfs is the league’s best tackle in Anderson’s view; Goedeke and Mauch make a high-end core.','The line lost 27 combined games at right tackle and guard last year, so simple health creates major upside.'],['Robinson is a fourth play caller in four years and may alter the run scheme.'],['A healthy season could leave Tampa No. 1.'],[299,395]),
  E('IND',3,'2','Could finish first','Best run-blocking unit',['Quenton Nelson','Jalen Travis','Shane Steichen','Daniel Jones'],['Best run-blocking line in the league; Nelson remains the centerpiece.','Four of five starters return, including Travis, and Steichen’s scheme helped create a historic offense for half a season.'],['The offense still needs competent quarterback play to cash the line advantage.'],['A merely functional Jones is enough for this group to power a top offense.'],[404,467]),
  E('LAC',4,'2','Could finish first','Elite tackles, injured center',['Rashawn Slater','Joe Alt','Tyler Biadasz','Jake Slaughter','Mike McDaniel','Charlie Kolar','Alec Ingold'],['A healthy Slater/Alt duo has Hall-of-Fame-level tackle upside.','McDaniel, Kolar and Ingold should make the run game and protection friendlier.'],['Slater is returning from a patellar injury, Alt missed half a season with an ankle problem and new center Biadasz suffered an indefinite knee injury.','Rookie Slaughter may have to start and the interior is the weak link.'],['Ranking was completed before the Biadasz injury; Anderson explicitly revises the live expectation to roughly eighth–tenth until health improves.'],[473,635]),
  E('PHI',5,'3','Old stalwarts','Elite edges, thinner foundation',['Jordan Mailata','Lane Johnson','Tyler Steen','Jeff Stoutland','Jalen Hurts'],['Mailata is an elite run blocker and Johnson remains a premier pass protector.'],['Johnson faces a suspension and possible final season; Steen is a weak link, injuries exposed no depth, and legendary coach Stoutland retired after a contentious finish.','A pass-heavier new offense is not an ideal Hurts fit.'],['More top-five than No. 1 after ranking first last year.'],[650,744]),
  E('BUF',6,'3','Old stalwarts','Continuity and collective run blocking',['Aaron Kromer','Josh Allen'],['The same five starters stayed unusually healthy and together for three years.','Collective run blocking, Allen and blocking tight ends make the whole greater than the individual names.'],['One starter and respected coach Kromer are gone, slightly reducing the continuity advantage.'],['Anderson sees Buffalo as the perennial fifth-to-seventh line.'],[744,806]),
  E('CHI',7,'3','Old stalwarts','Right-side strength',['Joe Thuney','Drew Dalman','Ozzy Trapilo','Darnell Wright','Ben Johnson','Caleb Williams'],['Thuney ranked third by PFF and won Anderson’s 40–1 Protector of the Year bet.','Wright and the right side form the best run-blocking strength; Johnson’s condensed/play-action design helps Williams.'],['Dalman retired early and Trapilo must return cleanly from injury.'],['A strong line whose main risk is absorbing a center transition.'],[806,866]),
  E('KC',8,'4','Good, not great','Interior excellence',['Creed Humphrey','Trey Smith','Josh Simmons','Jawaan Taylor','Kenneth Walker'],['Humphrey is the best center by a wide margin, Smith is improving and Simmons is developing at tackle.','Taylor’s departure is addition by subtraction.'],['The run game succeeded but produced few explosives; tackle quality still prevents a top tier.'],['Walker could add the explosives the blocking already creates.'],[869,930]),
  E('SF',9,'4','Good, not great','The Trent Williams fulcrum',['Trent Williams','Brock Purdy','Kyle Shanahan'],['Williams remains an elite run/pass tackle and has played 14-plus games in five of six years.','Shanahan’s scheme and Purdy’s processing help the remaining unit.'],['Williams is 38, has injury risk and is slipping from his peak.'],['Purdy is cited at 44–10 with Williams and 2–7 without him; an absence turns this into a bottom-ten line.'],[930,1000]),
  E('LAR',10,'4','Good, not great','Strong interior, fragile edges',['Kevin Dotson','Alaric Jackson','Sean McVay','Matthew Stafford'],['All five starters carried top-ten PFF grades; Dotson leads a powerful run-blocking interior and McVay helps the structure.'],['The tackles are less secure, Jackson carries injury/off-field concern and depth is poor.','Stafford is especially vulnerable when pressure breaks through.'],['Very good when the intended five play, brittle beyond them.'],[1000,1070]),
  E('ATL',11,'4','Good, not great','Established core, coaching change',['Chris Lindstrom','Dwayne Ledford','Bill Callahan','Jawaan Taylor'],['The unit has ranked roughly seventh–11th for four years; Lindstrom is the star.','Callahan is a legendary line coach.'],['Ledford left, making the coaching transition meaningful; Taylor is a personnel negative.'],['The range stays familiar, but continuity is less clean.'],[1070,1140]),
  E('DAL',12,'4','Good, not great','Interior/run-game bet',['Clayton Adams','Tyler Guyton','Tyler Smith','Cooper Beebe','Tyler Booker','Dak Prescott'],['Adams brings a creative downhill/gap run scheme; the young interior has real upside.','Prescott grades exceptionally under pressure.'],['Tackle and edge pass protection are the obvious weakness.'],['A scheme-and-interior bet rather than five proven blockers.'],[1140,1220]),
  E('MIN',13,'5A','Wild cards Anderson believes','Top tackle duo if healthy',['Christian Darrisaw','Brian O’Neill','Ryan Kelly','Frank Smith','Mike McDaniel'],['Darrisaw and O’Neill can be a top-five run-blocking tackle duo; Smith brings McDaniel-influenced run design.'],['Darrisaw has played only 29 games in two years; Kelly retired and the entire unit spent last season injured.'],['Health, not talent, keeps Minnesota outside the top ten.'],[1232,1328]),
  E('NO',14,'5A','Wild cards Anderson believes','No star, no glaring weak link',['David Edwards','Kellen Moore','Jordan Tyson','Alvin Kamara'],['Four self-drafted starters were top-two-round picks, including two recent first-round tackles; Edwards helps at left guard.','Moore’s tempo can reduce pressure.'],['No clear star; surrounding injuries to Kamara and Tyson can make the offense less line-friendly.'],['Balanced competence across five spots drives the optimistic rank.'],[1328,1410]),
  E('BAL',15,'5A','Wild cards Anderson believes','Rebuilt interior',['Ronnie Stanley','Tyler Linderbaum','Ethan Pocic','John Simpson','Dwayne Ledford','Declan Doyle','Derrick Henry','Lamar Jackson'],['Stanley can still anchor the edge; Pocic is an acceptable center replacement.','Two new guards plus Ledford/Doyle coaching and the Henry/Jackson run threat give top-ten upside.'],['Linderbaum is gone, Stanley’s health remains a risk and the guards must gel.'],['Outside models place the current talent in the high 20s; Anderson is projecting the environment and rebuild.'],[1410,1450]),
  E('SEA',16,'5B','Wild cards Anderson doubts','Continuity versus scheme loss',['Grey Zabel','Clint Kubiak','Sam Darnold'],['All five starters return and Zabel should improve in year two.','A jump from last year’s No. 31 rank to 16 is already substantial.'],['The other guard remains a glaring weakness; Kubiak is gone.','If Seattle trails more often, obvious passing situations can expose both the line and Darnold.'],['The ranking prices meaningful regression from the perfect lead-heavy environment.'],[1450,1558]),
  E('DET',17,'5B','Wild cards Anderson doubts','Former No. 1 in transition',['Penei Sewell','Blake Miller','Cade Mays','Jared Goff'],['Sewell remains a star.'],['Sewell moves to left tackle, Miller is a rookie right tackle and Mays may miss half the season; the interior keeps turning over.','Goff handles quick interior pressure poorly.'],['From No. 1 two years ago to the bottom half; Anderson calls this one of the league’s most important falls.'],[1559,1637]),
  E('PIT',18,'5B','Wild cards Anderson doubts','Four positions changing',['Zach Frazier','Aaron Rodgers'],['Frazier is a strong young center and the individual players are likable.'],['The right guard and tackle both flip to the left, a rookie may start at right tackle, four spots change positions and a new coach arrives.','Rodgers no longer protects a line the way he once did.'],['Some analysts rank Pittsburgh third or fourth; Anderson sees too much simultaneous change.'],[1637,1670]),
  E('NYG',19,'6','Much better than last year','Andrew Thomas plus upside',['Andrew Thomas','Francis Mauigoa','Matt Nagy'],['Thomas is a superstar when available; the No. 10 pick Mauigoa adds talent.'],['Thomas played only 29 games over three years; the run game is weaker and Nagy’s offense is a negative.'],['A major rise from the bottom group, but still dependent on one fragile star.'],[1673,1745]),
  E('CIN',20,'6','Much better than last year','Continuity at last',['Joe Burrow'],['All five starters return together for the first time in Burrow’s career.','Late-season run improvement and more under-center work point toward average play.'],['The line has been bottom-five nearly every year and must prove the late improvement is real.'],['Average would be transformational enough to reopen an MVP/playoff case.'],[1745,1780]),
  E('NE',21,'6','Much better than last year','Real additions, health caveats',['Will Campbell','Alijah Vera-Tucker'],['The line moved from dead last to 11th before the playoffs; Vera-Tucker is top-ten quality when healthy.'],['Campbell struggled in the playoffs; Vera-Tucker has played only 29 games in four years.'],['Improvement is banked, but durability caps the rank.'],[1780,1793]),
  E('LV',22,'7','Average would surprise','Kubiak floor',['Clint Kubiak','Rick Dennison','Tyler Linderbaum','Kolton Miller'],['Kubiak and Dennison should establish a run-game floor; Linderbaum strengthens the middle.','Miller is an elite pass protector when available.'],['Miller played only four games and the group still lacks five dependable pieces.'],['Finishing outside the bottom ten would count as a successful projection.'],[1793,1845]),
  E('NYJ',23,'7','Average would surprise','First-round tackle bet',['Olu Fashanu','Armand Membou','Frank Reich'],['Fashanu and Membou give the Jets two premium young tackles.'],['The rest of the line is uncertain; Reich’s recent offenses and post-departure improvements worry Anderson.'],['High draft capital creates a path, but coaching lowers confidence.'],[1845,1880]),
  E('ARI',24,'7','Average would surprise','Stuck in the 20s',['Chase Bisontis','Clayton Adams'],[],['Arizona has finished 22nd or worse in five straight editions; No. 34 pick Bisontis is already out for the year.','The run game has not recovered since Adams left.'],['Not disastrous, but there is little positive catalyst.'],[1883,1927]),
  E('HOU',25,'7','Average would surprise','Depth and a tone-setting rookie',['Keelan Rutledge','Braden Smith','Ed Ingram','Wyatt Teller'],['The rookie center is framed as a culture changer and potential long-term anchor.','Smith, Ingram and Teller have each participated in strong lines; eight-to-ten viable names create depth.'],['Smith must stay healthy and Houston still has to identify its best five.'],['The name “Keelan Rutledge” is transcript-derived and retained as a possible transcription error; moving from 32nd to 25th would still be significant.'],[1928,1988]),
  E('MIA',26,'8','All downside from here','Quarterback/scheme change',['Patrick Paul','Aaron Brewer','Kadyn Proctor','Mike McDaniel','Tua Tagovailoa'],['Brewer may be the league’s best center and Paul/Proctor offer young size.'],['Losing McDaniel and Tua’s quick-release structure means the new quarterback may hold the ball or scramble into pressure.'],['Personnel is not hopeless; context makes the projection worse.'],[1991,2050]),
  E('CAR',27,'8','All downside from here','Four injured cornerstones',['Ikem Ekwonu','Taylor Moton','Rasheed Walker','Bryce Young'],['A first-round addition and Walker provide emergency options.'],['Ekwonu has an Achilles injury, Moton faces blood-clot uncertainty and both guards are hurt; four intended starters carry health problems.','Young is vulnerable behind disruption.'],['Injury concentration turns a once-promising group into downside.'],[2050,2110]),
  E('GB',28,'8','All downside from here','One healthy answer missing',['Zach Tom','Jordan Morgan','Matt LaFleur'],['LaFleur can scheme around some line limitations; Tom is the one proven high-level player.'],['Tom is returning from a patellar injury, Morgan disappointed and moved to left tackle, and the other four spots look rough.'],['A customary fringe-top-ten unit plunges to 28th; Anderson says he will not invest in Green Bay futures.'],[2110,2180]),
  E('WAS',29,'8','All downside from here','Lost its pass-protection anchor',['Laremy Tunsil'],[],['Tunsil’s season-ending injury removes one of football’s best pass protectors.','External grades cited in the episode fell from top 20 to last and from 11th to 22nd.'],['Anderson calls the outlook potentially doomed.'],[2180,2200]),
  E('JAX',30,'9','Bottom of the barrel','Winning in spite of it',['Trevor Lawrence','Liam Coen','Cole Van Lanen'],['Lawrence’s quick release and Coen’s scheme reduce the damage.'],['There is no unit strength; Van Lanen may be the best blocker but is on PUP with a potentially long absence.'],['Thirteen wins came in spite of the line, not because of it.'],[2200,2268]),
  E('TEN',31,'9','Bottom of the barrel','One good guard',['Peter Skoronski','Kevin Zeitler','Bill Callahan'],['Skoronski is the best lineman among the bottom two teams.'],['Zeitler and Callahan are gone, the tackles are poor and quarterbacks hold the ball too long.'],['Bad protection and quarterback behavior form a destructive feedback loop.'],[2268,2325]),
  E('CLE',32,'9','Bottom of the barrel','A complete reset',['Spencer Fano'],['Returning none of last year’s starters is the one optimistic fact because the old line was a disaster.'],['The replacement names are injury-prone; No. 9 pick Fano may be developmental and has no stable group around him.'],['Anderson expects the reset to go badly.'],[2268,2332]),
];

export const skillEvidence: Evidence[] = [
  E('LAR',1,'1','MVP starter pack','League’s deepest complete group',['Puka Nacua','Davante Adams','Kyren Williams','Blake Corum','Colby Parkinson','Tyler Higbee','Terrance Ferguson','Davis Allen'],['Nacua wins on every route, third down and as a blocker; Adams remains a red-zone weapon.','Williams and Corum both graded top 15 by PFF, creating a top-eight backfield.','Parkinson and Higbee are balanced, Ferguson adds vertical breakout potential, and even TE4 Allen could be another team’s TE2.'],['Adams is aging, but depth sharply limits the downside.'],['Five playable tight ends enable 13 personnel; Anderson calls this No. 1 by a wide margin.'],[191,299]),
  E('DET',2,'2','Loaded and deep','Elite stars, slightly thinner depth',['Jahmyr Gibbs','Isiah Pacheco','David Montgomery','Jameson Williams','Amon-Ra St. Brown','Sam LaPorta','Isaac TeSlaa','Brock Wright','Tyler Conklin','Drew Petzing','Trey McBride'],['Gibbs has rare game speed and room for a bigger load; St. Brown is a top-five receiver who also blocks and wins through routes/hands.','Williams supplies speed, LaPorta has breakout potential in Petzing’s tight-end lineage, and Wright/Conklin add blocking.'],['Pacheco is a downgrade from Montgomery and the line is worse; the group is less deep than Los Angeles.'],['The transcript’s “Caslat” is normalized to TeSlaa with caution; the cited player scored six TDs.'],[302,410]),
  E('MIN',3,'2','Loaded and deep','Formation-proof versatility',['Justin Jefferson','Jordan Addison','Jauan Jennings','T.J. Hockenson','Josh Oliver','Aaron Jones','Jordan Mason','Frank Smith'],['Jefferson remained elite through poor quarterback play; Addison and Jennings offer complementary receiving.','Hockenson plus elite blocker Oliver supports multiple personnel packages.','Jones adds receiving while Mason supplies power in Smith’s run system.'],['Jones is aging and the room still depends heavily on Jefferson staying dominant.'],['The number of viable options and formations is the core advantage.'],[410,490]),
  E('DAL',4,'3','Fantasy-football island','Receiver depth and top-end punch',['CeeDee Lamb','George Pickens','KaVontae Turpin','Marquez Valdes-Scantling','Ryan Flournoy'],['Lamb and Pickens form an elite pair; Pickens’ metrics validate more than a secondary role.','Turpin, Valdes-Scantling and Flournoy give the receiver room actual depth.'],['Lamb played hurt; the backfield and tight ends are more “fine” than special.'],['The top two receivers drive the rank, but Dallas has more underneath them than Cincinnati.'],[491,595]),
  E('CIN',5,'3','Fantasy-football island','Best lead receiver, shallow support',['Ja’Marr Chase','Tee Higgins'],['Chase is Anderson’s best receiver; Higgins is a high-quality No. 2.'],['Higgins has injury history and is not viewed as a true No. 1; there is little wide-receiver depth.'],['Running back and tight end are acceptable, leaving a star-led rather than deep profile.'],[491,595]),
  E('ATL',6,'3','Fantasy-football island','Elite triplet',['Bijan Robinson','Brian Robinson Jr.','Drake London','Kyle Pitts','Austin Hooper','Jahan Dotson','Darnell Mooney'],['Bijan is Anderson’s No. 1 all-around back and a true receiving weapon; Brian Robinson creates a tandem.','London is top ten and Pitts functions as an effective WR2, with Hooper supporting tight end.'],['Receiver depth after London is awful; Dotson and Mooney do not solve it.'],['The triplet is elite enough to carry a shallow perimeter group.'],[595,730]),
  E('ARI',7,'3','Fantasy-football island','High-upside young stars',['Jeremiyah Love','James Conner','Tyler Allgeier','Trey McBride','Michael Wilson','Marvin Harrison Jr.','Jacoby Brissett','Kyler Murray'],['McBride is a premier tight end; Wilson broke out and has chemistry with Brissett.','Harrison still gets open and the Conner/Allgeier analytics are strong.'],['Love is a rookie with a high-ankle issue and only 14 cited carries; Harrison’s fit with Murray/the offense has disappointed.','Health is the broad risk.'],['A high-ceiling room whose ordering assumes the young back and receivers convert talent.'],[730,810]),
  E('SF',8,'3','Fantasy-football island','Great designer, fragile veterans',['Christian McCaffrey','George Kittle','Jake Tonges','Luke Farrell','Mike Evans','Deebo Samuel','Kyle Juszczyk','Kyle Shanahan'],['McCaffrey still creates enormous receiving value; Kittle is Anderson’s No. 1 all-around tight end and Juszczyk the best fullback.','Tonges is useful, Farrell blocks and Shanahan amplifies the collection.'],['McCaffrey’s rushing has declined; Kittle is coming off an Achilles injury, while Evans and Samuel are older/injured.','Young receivers are unproven.'],['Wide range: the healthiest version can finish near the top.'],[810,910]),
  E('NE',9,'4','One star, no weakness','Depth that cascades roles',['A.J. Brown','Romeo Doubs','Kayshon Boutte','Mack Hollins','Demario Douglas','Kyle Williams','Rhamondre Stevenson','TreVeyon Henderson'],['Brown supplies a true star; Doubs can play outside, Boutte becomes a WR3, Hollins blocks, Douglas provides gadget value and Williams adds youth.','Stevenson/Henderson make a deep backfield.'],['Brown’s health is the main concentrated risk.'],['Adding one star moves every other player into a better role and lifts New England from 25th to ninth.'],[911,1033]),
  E('PHI',10,'4','One star, no weakness','Barkley and a remade receiver room',['DeVonta Smith','Dontayvion Wicks','Marquise Brown','Makai Lemon','Saquon Barkley','Johnny Mundt'],['Barkley remains the star; Smith, Wicks, Brown and Lemon offer varied receiving traits.'],['Without A.J. Brown, Smith must be a true WR1 despite frame concerns.','Three receiving tight ends block poorly; Mundt is effectively the only blocking specialist, limiting personnel flexibility.'],['The fall from last year’s No. 1 is almost entirely the Brown transaction plus tight-end role imbalance.'],[917,1033]),
  E('CHI',11,'4','One star, no weakness','Tight-end centerpiece',['Colston Loveland','Cole Kmet','Rome Odunze','Luther Burden III','Kyle Monangai'],['Loveland is counted as a top-three, complete tight end; Kmet is an unusually strong TE2.','Odunze and Burden have high draft capital and the two-back structure is sound.'],['The young receivers still have to prove production; Monangai’s health bears watching.'],['Tight-end depth makes the room more complete than a fantasy-only look suggests.'],[1034,1095]),
  E('GB',12,'4','One star, no weakness','Top-heavy and less certain',['Josh Jacobs','Tucker Kraft','Christian Watson','Matthew Golden','Jayden Reed'],['Jacobs remains the proven strength; Watson and Reed provide complementary traits.'],['Kraft is injured with no tight-end depth, Watson’s availability is unreliable, and Golden did not take the expected step.'],['A room once defined by options now feels top-heavy.'],[1082,1187]),
  E('JAX',13,'5','Plenty to like','Many answers, rebound required',['Parker Washington','Brian Thomas Jr.','Jakobi Meyers','Travis Hunter','Travis Etienne','Bhayshul Tuten'],['Washington broke out; Meyers fills a missing reliable role and Hunter adds rare upside.'],['Thomas had a terrible, drop-heavy year and must recover; Etienne and Tuten are gone from the backfield.'],['The rank bets that talent plus role balance outweighs last year’s receiver failure.'],[1211,1280]),
  E('SEA',14,'5','Plenty to like','Best receiver, uncertain backs',['Jaxon Smith-Njigba','A.J. Barner','Rashid Shaheed','Kenneth Walker III','Zach Charbonnet','Jadarian Price'],['Smith-Njigba is the reigning Offensive Player of the Year and belongs in the No. 1 receiver conversation.','Barner is underrated and Shaheed provides vertical speed.'],['Walker is gone, Charbonnet is hurt and first-round rookie Price has never carried a lead load.'],['The passing weapons are excellent; the running-back room holds the rank down.'],[1217,1410]),
  E('BUF',15,'5','Plenty to like','Blocking and tight ends over receivers',['DJ Moore','James Cook','Dalton Kincaid','Dawson Knox','Jackson Hawes'],['Kincaid has top-five upside when healthy; Knox is a strong TE2 and Hawes graded top five as a blocker.','Moore and the receiver group support the run through blocking.'],['Moore profiles more as a WR2; the room lacks a vertical lead receiver.','Cook’s top-line output is helped by line play and Josh Allen.'],['A functional football group that looks weaker through a fantasy-receiver lens.'],[1364,1460]),
  E('TB',16,'5','Plenty to like','Healthy depth question',['Chris Godwin','Emeka Egbuka','Jalen McMillan','Tez Johnson','Hayden Hurst','Bucky Irving','Kenneth Gainwell'],['Godwin/Egbuka can form a quality pair; McMillan, Johnson and Hurst provide depth.','Irving and Gainwell complement each other in the backfield.'],['The top receivers carry health concerns and may both be better as No. 2s than a true No. 1.'],['Solid across roles without a unit Anderson loves.'],[1217,1355]),
  E('DEN',17,'5','Plenty to like','Waddle changes the geometry',['Jaylen Waddle','Courtland Sutton','Pat Bryant','Marvin Mims Jr.','Troy Franklin','Evan Engram','Nate Adkins','Adam Trautman','Bo Nix'],['Waddle adds zone and vertical speed, moving Sutton into a better WR2/man role.','Bryant, Mims and Franklin add receiver depth; Engram catches while Adkins/Trautman block.'],['The backs and non-Engram tight ends do not add much star value.'],['A more complementary group designed to unlock Nix’s deep passing.'],[1270,1364]),
  E('IND',18,'6','What average looks like','Late veteran addition',['Jonathan Taylor','Tyler Warren','Alec Pierce','Josh Downs','Michael Pittman Jr.','Keenan Allen'],['Taylor remains highly productive; Pierce and Downs grade well analytically.','Allen adds the reliable “vegetables” and middle-of-field work the room lacked.'],['Taylor benefits from scheme/line; Warren may be only a 10th–15th tight end and blocks poorly, while Pittman profiles as a WR2.'],['Anderson notes this may be slightly low after Allen’s late addition.'],[1496,1690]),
  E('PIT',19,'6','What average looks like','Sevens everywhere',['Jaylen Warren','Rico Dowdle','Darnell Washington','Pat Freiermuth','DK Metcalf'],['Warren is underrated, Dowdle is serviceable, Washington blocks and Freiermuth is a solid receiver.'],['Metcalf is viewed as a WR2 rather than a true lead; tight-end depth was lost.'],['Anderson calls it the most average collection: almost every role grades around seven out of ten.'],[1502,1600]),
  E('WAS',20,'6','What average looks like','Two receivers, little else',['Stefon Diggs','Terry McLaurin'],['Diggs and McLaurin are both top-20-caliber receivers.'],['Washington lacks an NFL-quality starting answer at running back or tight end.'],['A strong duo cannot fully cover empty supporting positions.'],[1600,1710]),
  E('LAC',21,'7','AFC contender red flags','McDaniel-specific role players',['Charlie Kolar','Alec Ingold','David Njoku','Oronde Gadsden II','Omarion Hampton','Ladd McConkey','Keenan Allen','Mike McDaniel'],['Kolar functions as a sixth lineman, Ingold supports the backfield, and Njoku/Gadsden give tight-end variety.','A healthy Hampton has breakout potential and McConkey is an ideal McDaniel receiver.'],['Keenan Allen is gone and there is almost no wide-receiver depth behind McConkey.'],['A coherent scheme fit that can rise toward average if Hampton hits.'],[1712,1830]),
  E('BAL',22,'7','AFC contender red flags','Elite back, depleted pass catchers',['Zay Flowers','Rashod Bateman','Mark Andrews','Isaiah Likely','Charlie Kolar','Derrick Henry'],['Henry remains an elite runner.'],['Flowers is not a true WR1, Bateman is ineffective/injured and the rookies are unproven.','Andrews is older and no longer top five; Likely and Kolar are gone, gutting last year’s No. 1 tight-end room.'],['A fall from top three is explained by losses, age and bottom-five receiver depth.'],[1715,1835]),
  E('KC',23,'7','AFC contender red flags','Backfield upgrade, passing drought',['Travis Kelce','Rashee Rice','Xavier Worthy','Kenneth Walker III'],['Walker adds explosive, highly graded running-back talent.'],['Kelce now looks average, Rice has lost speed/YAC after the knee injury, and Worthy remains unproven.','The offense lacks dependable pass catchers.'],['Running-back improvement cannot carry the category because Anderson weights receivers and tight ends more heavily.'],[1835,1933]),
  E('HOU',24,'7','AFC contender red flags','One receiver only',['Nico Collins','David Montgomery'],['Collins is a true star; Montgomery improves the backfield.'],['Collins has health risk, Montgomery is not a lead back, and the episode finds almost nothing else to trust.'],['Anderson says the honest talent rank may be closer to 27th.'],[1925,2026]),
  E('NYJ',25,'8','Young talent, not there yet','Draft-capital upside',['Breece Hall','Garrett Wilson','Kenyon Sadiq','Cooper','Adonai Mitchell','Mason Taylor'],['Hall is a balanced back and Wilson has lead-receiver talent.','Multiple first-round investments plus Mitchell and Taylor provide developmental upside.'],['Wilson still needs to convert talent into sustained production; most of the supporting case is projection.'],['The transcript’s “Cooper” reference is retained without inventing a first name.'],[2027,2100]),
  E('LV',26,'8','Young talent, not there yet','Two premium young pieces',['Ashton Jeanty','Brock Bowers','Jack Bech','Jalen Nailor','Tre Tucker'],['Bowers is a top-five tight end; Jeanty offers receiving value.'],['Jeanty disappointed as a runner and blocker; Bech, Nailor and Tucker look like three WR3s with no lead receiver.'],['Premium draft talent exists, but the role distribution is badly incomplete.'],[2036,2150]),
  E('NO',27,'8','Young talent, not there yet','Health and aging erase upside',['Chris Olave','Jordan Tyson','Alvin Kamara'],['Olave has high-end receiving ability if available.'],['Olave’s injury history persists, Tyson has a fourth hamstring issue and Kamara appears washed.'],['One transcript player reference around the backfield is garbled and intentionally omitted from the named facts rather than guessed.'],[2150,2188]),
  E('CAR',28,'8','Young talent, not there yet','A young receiver lead',['Tetairoa McMillan','Jalen Coker'],['McMillan is Anderson’s best player in this tier; Coker adds another legitimate receiver.'],['There are few other high-end answers across back, tight end and receiver depth.'],['Some talent, but not enough complete-unit strength.'],[2188,2218]),
  E('NYG',29,'9','One receiver is the hope','Nabers and injured maybes',['Malik Nabers','Theo Johnson','Isaiah Likely','Cam Skattebo'],['Nabers is a monster talent and the single credible source of a high ceiling.'],['Nabers’ health is central; Johnson, Likely and Skattebo also carry health/uncertainty.'],['Gallant sees more optimism in the supporting names; Anderson says the case is essentially Nabers alone.'],[2219,2268]),
  E('TEN',30,'9','One receiver is the hope','Rookie lead and a long build',['Carnell Tate','Wan’Dale Robinson'],['Tate projects as a reliable first-round receiver; Robinson supplies underneath production.'],['The rest of the group needs time and offers little current proof.'],['Moving from 32nd to 30th is improvement, not readiness.'],[2268,2300]),
  E('CLE',31,'9','One receiver is the hope','Interesting rookies, no proof',['KC Concepcion','Harold Fannin Jr.'],['Concepcion drew strong camp/preseason buzz; Fannin adds draft-capital talent.'],['Almost the whole case is unproven projection, with no established star or depth.'],['The transcript’s second player name is garbled; Fannin is the cautious normalization and remains flagged in Sources & QA.'],[2219,2300]),
  E('MIA',32,'10','The teardown','Achane alone',['De’Von Achane','Malik Washington','Jalen Tolbert','Tutu Atwell','Jalen Reagor','Terrace Marshall Jr.','Greg Dulcich','Mike McDaniel'],['Achane is the sole established difference-maker.'],['The receiver list is dominated by reclamation-level players, Dulcich has never broken through and the rookies are unknown.','Losing McDaniel removes the system that elevated the entire room.'],['A collapse from No. 6 to No. 32; Anderson says the roster construction looks like a team not trying to contend.'],[2303,2400]),
];

export const categories: { id: CategoryId; label: string; short: string; evidence: Evidence[]; methodology: string }[] = [
  { id:'qb', label:'Quarterbacks', short:'QB', evidence:qbEvidence, methodology:'Starter and room quality, production, traits, health, playoff proof, trajectory and the degree to which the player creates beyond his environment.' },
  { id:'coaching', label:'Coaching staffs', short:'Coach', evidence:coachingEvidence, methodology:'Whole-staff value: head coaching, game management, offensive and defensive play calling, hiring, culture, special teams and position-coach effects. Offense receives extra weight.' },
  { id:'ol', label:'Offensive lines', short:'OL', evidence:olEvidence, methodology:'Five-man weak-link quality, continuity, injuries and depth, coaching/scheme, with pass protection weighted for ceiling and run blocking for floor.' },
  { id:'skill', label:'Skill positions', short:'Skill', evidence:skillEvidence, methodology:'Every non-QB/non-line weapon. Receivers receive roughly half the weight; tight ends matter at least as much as backs because blocking and personnel flexibility count. Stars matter, depth matters more.' },
];

export const evidenceByCategory = Object.fromEntries(categories.map(c => [c.id, Object.fromEntries(c.evidence.map(e => [e.team, e]))])) as Record<CategoryId,Record<string,Evidence>>;

export function compositeFor(abbr: string) {
  const ranks = categories.map(c => evidenceByCategory[c.id][abbr].rank);
  return Number((ranks.reduce((a,b)=>a+b,0)/ranks.length).toFixed(2));
}

export const claimCount = categories.reduce((total,c) => total + c.evidence.reduce((n,e) => n + e.positives.length + e.concerns.length + e.context.length,0),0);
